### PR TITLE
replace uses of deprecated `std::iter::range`

### PR DESCRIPTION
**Pull request by apasel422**

### CODE REVIEW

**Comment by FlashCat** [comment]
r? @Gankro

(I've picked a reviewer for you, use r? to override)

**Comment by Gankra** [comment]
:cold_sweat: 

This is a pretty tricky patch.

I dunno if I'm qualified to review it.

**Comment by Gankra** [comment]
@FlashCat r+

**Comment by FlashCat** [comment]
:pushpin: Commit f016811 has been approved by `Gankro`

**Comment by FlashCat** [comment]
:hourglass: Testing commit f016811 with merge 4eb09e1...

**Comment by FlashCat** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/contain-rs/blist/builds/55177108)

**Pull request merged**
