### PR TITLE
trivial whitespace change to test homu on

### PR DESCRIPTION
**Pull request by Gankra**

### CODE REVIEW

**Comment by FlashCat** [comment]
r? @huonw

(I've picked a reviewer for you, use r? to override)

**Comment by Gankra** [comment]
@FlashCat r+

**Comment by FlashCat** [comment]
:pushpin: Commit 4c6a2b9 has been approved by `Gankro`

**Comment by FlashCat** [comment]
:hourglass: Testing commit 4c6a2b9 with merge 4227a12...

**Comment by FlashCat** [comment]
:hourglass: Testing commit 4c6a2b9 with merge d30b673...

**Comment by FlashCat** [comment]
:hourglass: Testing commit 4c6a2b9 with merge cf272a9...

**Comment by huonw** [comment]
(Sorry for this, trying to work out why @FlashCat is unhappy.)

**Comment by FlashCat** [comment]
:hourglass: Testing commit 4c6a2b9 with merge cb56794...

**Comment by FlashCat** [comment]
:hourglass: Testing commit 4c6a2b9 with merge cacb8ea...

**Comment by FlashCat** [comment]
:hourglass: Testing commit 4c6a2b9 with merge 7c66157...

**Comment by FlashCat** [comment]
:hourglass: Testing commit 4c6a2b9 with merge 9476c1e...

**Comment by FlashCat** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/contain-rs/blist/builds/54994625)

**Comment by FlashCat** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/contain-rs/blist/builds/54994625)

**Comment by huonw** [comment]
\o/

**Comment by huonw** [comment]
The problem is how the travis tokens work. They're used by travis to send a authentication message to Homu, so Homu can check to see it's really travis talking. Since @Gankro activated travis for this repo (I assume) it is deciding to send the message computed from @Gankro's token, but Homu is configured to use @FlashCat's one, so the check failed.

I think I've manually updated all the repos with travis activated to use @FlashCat's (one can manually change the token on the Travis CI page under github.com/contain-rs/NAME/settings/hooks), and I assume this can be mitigated by activating travis via @FlashCat's account in future.

**Pull request merged**
